# Change these first
owner: DismalShadowX # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: DismalShadowX

assignees: # Users to assign downtime issues (optional)
  - DismalShadowX

sites:
  - name: Home Web
    url: https://everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Shadow's Blogosphere
    url: https://blog.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Mastodon Health
    url: https://everythingbagel.social/api/v1/streaming/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Pixelfed Health
    url: https://pixel.everythingbagel.me/api/service/health-check
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Hub
    url: https://hub.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Video
    url: https://video.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Shadow Does Streams
    url: https://stream.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Press
    url: https://press.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Events
    url: https://events.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Elk
    url: https://elk.everythingbagel.social
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Phanpy
    url: https://phanpy.everythingbagel.social
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Cloud
    url: https://cloud.everythingbagel.me/status.php
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: In Light & In Shadow
    url: https://scribe.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000    

  - name: Library of Infinity
    url: https://book.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Helpdesk
    url: https://support.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000    

  - name: Background queues
    url: https://everythingbagel.social/sidekiq/stats
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: S3 Media Storage
    url: https://ams1.vultrobjects.com
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  # In Development Sites
  - name: Dev Web
    url: https://dev.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: The Empty
    url: https://test.everythingbagel.me
    expectedStatusCodes:
      - 200
      - 201
      - 404
    commitMessages:
      readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
      summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
      statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
      graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
    maxResponseTime: 5000
   
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.everythingbagel.me
  # favicon: https://everythingbagel.me/images/logo.png
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: |
    # See http://www.robotstxt.org/robotstxt.html for documentation on how to use the robots.txt file
    # For the complete list of user agents, visit https://status.everythingbagel.me/robots.txt
    # Block unauthorised use of this site as training material for AI
    # FAANG
    User-agent: Amazonbot
    Disallow: /
    User-agent: Applebot
    Disallow: /
    User-agent: FacebookBot
    Disallow: /
    ## Microsoft / OpenAI
    User-agent: GPTBot
    Disallow: /
    User-agent: ChatGPT-User
    Disallow: /
    ## Google
    User-agent: Google-Extended
    Disallow: /
    User-agent: AdsBot-Google
    Disallow: /
    # Others
    User-agent: anthropic-ai
    Disallow: /
    User-agent: Claude-Web
    Disallow: /
    User-agent: cohere-ai
    Disallow: /
    User-agent: Bytespider
    Disallow: /
    User-agent: Diffbot
    Disallow: /
    User-agent: Mediapartners-Google
    Disallow: /
    ## Common Crawl
    User-agent: CCBot
    Disallow: /
    User-agent: The Knowledge AI
    Disallow: /
    User-agent: Omgilibot
    Disallow: /
    User-agent: Omgili
    Disallow: /
    User-agent: panscient.com
    Disallow: /
    User-agent: PetalBot
    Disallow: /
    User-agent: Turnitin
    Disallow: /
    User-agent: PerplexityBot
    Disallow: /
    User-agent: YouBot
    Disallow: /
    # Default directives for specific User-agents
    User-agent: *
    Disallow: /media_proxy/
    Disallow: /interact/
    # Default directives for all other User-agents
    Disallow:
    # Wait 5 seconds between successive requests
    Crawl-delay: 5
    
  #theme: night #dark, light, night, ocean
  themeUrl: https://everythingbagel.me/css/dark.css
  apiBaseUrl: https://api.github.com
  #baseUrl: /upptime
  logoUrl: https://everythingbagel.me/images/bagel-banner.png
  name: Everything Monitor
  introTitle: "Website Status of the *Everything Bagel Realms*"
  introMessage: Welcome to the endpoint monitor of live databases.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: http://everythingbagel.me
    - title: Wiki
      href: http://wiki.everythingbagel.me
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  url: "Websites"
  footer: "Copyright © 2003-2024 Nathan Sparrow. All Rights Reserved.  \n**Everything Monitor** is a status page which uses **real-time** data from our [open source]($REPO), powered entirely by [GitHub](https://upptime.js.org/).  \nNo server required — just GitHub Actions, Issues, and Pages."
  activeIncidents: "Paw-sitive Updates: Active Incidents"
  allSystemsOperational: "🟢 Everything is in the paws of the purrfect system!"
  degradedPerformance: "🟡 Degraded Purrformance"
  completeOutage: "🔴 Complete Cat-astrophes"
  partialOutage: "🟠 Partial Cat-astrophes"
  incidentTitle: "Incident $NUMBER: Dive into the Details!"
  incidentDetails: "Detailed Overview of the Incident"
  incidentFixed: "All fixed up! 🎉"
  incidentOngoing: "Still in progress, hang tight! ⏳"
  incidentOpenedAt: "Incident opened at"
  incidentClosedAt: "Closed at"
  incidentViewOnGitHub: "🖥️ View and Subscribe on GitHub"
  incidentCommentSummary: "Commented at $DATE by $AUTHOR"
  incidentBack: "← Back to All Pawsitive Updates"
  pastIncidents: "Past Paw-sitive Cat-astrophes"
  pastIncidentsResolved: "✅ Resolved in $MINUTES minutes! ($POSTS posts)"
  liveStatus: "🐾 Current Status Purrformance!"
  overallUptimeTitle: "Overall Uptime Overview"
  averageResponseTimeTitle: "Average Response Time Insights"
  sevenDayResponseTime: "7-Day Response Time Report"
  history: "History"
  responseTimeMs: "Response Time (ms) - How fast are we?"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  liveStatusHtmlComment: "<!--live status-->"
  uptime: "All-time uptime"
  uptimeDay: "24-hour uptime"
  uptimeWeek: "7-day uptime"
  uptimeMonth: "30-day uptime"
  uptimeYear: "1-year uptime"
  up: "Up and Running! 🚀"
  down: "⚫ Consumed by the Void! We'll be back soon!"
  degraded: "Degraded Performance. We’re on it!"
  loading: "🐾 Loading... Hang tight!"
  rateLimitExceededIntro: "You've hit the request limit for the hour. Patience is a virtue!"
  rateLimitExceededWhatDoesErrorMean: "What does this mean?"
  rateLimitExceededErrorMeaning: "This website uses the GitHub API to fetch real-time status. You’ve hit the default limit of 60 requests/hour."
  rateLimitExceededErrorHowCanFix: "How can I solve this?"
  rateLimitExceededErrorFix: "Wait for the limit to reset or add a GitHub Personal Access Token for extra requests!"
  rateLimitExceededGeneratePAT: "Here's how to generate a Personal Access Token"
  rateLimitExceededHasSet: "You've already got a personal access token set!"
  rateLimitExceededRemoveToken: "Remove token if necessary"
  rateLimitExceededGitHubPAT: "Your GitHub Personal Access Token"
  rateLimitExceededCopyPastePAT: "Copy & Paste Your Token Here"
  rateLimitExceededSaveToken: "Save Token for Future Requests"
  errorTitle: "Oops! An Error Occurred 🐾"
  errorIntro: "We hit a snag while fetching the latest status."
  errorText: "Please try again in a few moments."
  errorHome: "Return to Dust"
  pastScheduledMaintenance: "Past Feline Fixes 🛠️"
  scheduledMaintenance: "Future Purrformance Checks"
  scheduledMaintenanceSummaryStarted: "Started at $DATE for $DURATION minutes. Stay tuned!"
  scheduledMaintenanceSummaryStarts: "Starts at $DATE for $DURATION minutes. Prepare for downtime!"
  startedAt: "Started at"
  startsAt: "Starts at"
  duration: "Duration"
  durationMin: "$DURATION minutes (We’ll be back before you know it!)"
  incidentCompleted: "Incident Completed Successfully! 🎉"
  incidentScheduled: "Incident Scheduled: Mark Your Calendars!"
  duration24H: "24 Hours"
  duration7D: "7 Days"
  duration30D: "30 Days"
  duration1Y: "1 Year"
  durationAll: "All Time"
  locale: "en-US"

workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"
