# Change these first
owner: DismalShadowX # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Everything Bagel
    url: https://everythingbagel.me
  - name: Everything Pixel
    url: https://pixel.everythingbagel.me/api/service/health-check
  - name: Everything Cloud
    url: https://cloud.everythingbagel.me
  - name: Everything Video
    url: https://video.everythingbagel.me
  - name: Mastodon Streaming API
    url: https://social.everythingbagel.me/api/v1/streaming/health
  - name: Elk
    url: https://elk.social.everythingbagel.me
  - name: Library of Infinite Realms
    url: https://book.everythingbagel.me
  - name: Shadow Does Streams
    url: https://stream.everythingbagel.me
  - name: Nathan's Ramblings
    url: https://video.everythingbagel.me
  - name: Background queues
    url: https://social.everythingbagel.me/sidekiq
  - name: S3 (Media Storage)
    url: https://ams1.vultrobjects.com
    
    maxResponseTime: 5000
    expectedStatusCodes:
      - 200
      - 201
      - 404
    assignees: # Users to assign downtime issues (optional)
      - DismalShadowX

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.everythingelbagel.me
  theme: dark
  #themeUrl: https://dismalshadowx.github.io/upptime/dark.css
  apiBaseUrl: https://api.github.com
  #baseUrl: /upptime
  logoUrl: https://cloud.everythingbagel.me/s/cbPdT7iSQD5jCkm #https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Everything Status
  introTitle: "**Everything Status** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: http://everythingbagel.me
    - title: Wiki
      href: http://wiki.everythingbagel.me
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
