# Change these first
owner: DismalShadowX # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: DismalShadowX

assignees: # Users to assign downtime issues (optional)
  - DismalShadowX

sites:
  - name: Home Web
    url: https://everythingbagel.me
    faviconSvg: <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Homepage</title><path d="M1.992.034C1.217.166.602.841.416 1.769.388 1.901.36 21.858.388 23.895c0 .181 0 .181.923-.593.497-.416 1.328-1.128 1.801-1.516.34-.28.626-.543.637-.576.011-.039.022-1.148.017-2.466L3.76 16.35h1.516c.829 0 1.52.022 1.537.044.017.021.028.538.022 1.142 0 .61.011 1.104.022 1.104.017 0 .643-.522.725-.604.017-.017.401-.335.851-.714.923-.77.917-.764 1.373-1.148.28-.236.34-.264.412-.203.072.066 2.878 2.421 3.592 3.02a1239.37 1239.37 0 0 1 3.932 3.306c.003.003 2.02 1.74 2.076 1.702.021-.01.038-3.333.038-7.38-.006-6.574.005-7.365.082-7.381.044-.011.895-.017 1.884-.017h1.801l-.022-3.761c-.005-2.07-.033-3.817-.05-3.877-.142-.495-.51-1.022-.883-1.28-.473-.318.164-.302-10.566-.302-5.442-.005-9.99.011-10.11.033Z"/></svg>
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Shadow's Blogosphere
    url: https://blog.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Mastodon Health
    url: https://everythingbagel.social/api/v1/streaming/health
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Pixelfed Health
    url: https://pixel.everythingbagel.me/api/service/health-check
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Hub
    url: https://hub.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Video
    url: https://video.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Shadow Does Streams
    url: https://stream.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Press
    url: https://press.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Events
    url: https://events.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Elk
    url: https://elk.everythingbagel.social
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Phanpy
    url: https://phanpy.everythingbagel.social
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Everything Cloud
    url: https://cloud.everythingbagel.me/status.php
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: In Light & In Shadow
    url: https://scribe.everythingbagel.me/ghost/api/v3/admin
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000    

  - name: Library of Infinity
    url: https://book.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: Helpdesk
    url: https://support.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000    

  - name: Background queues
    url: https://everythingbagel.social/sidekiq/stats
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: S3 Media Storage
    url: https://ams1.vultrobjects.com
    faviconSvg: <svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Amazon S3</title><path d="M20.913 13.147l.12-.895c.947.576 1.258.922 1.354 1.071-.16.031-.562.046-1.474-.176zm-2.174 7.988a.547.547 0 0 0-.005.073c0 .084-.207.405-1.124.768a10.28 10.28 0 0 1-1.438.432c-1.405.325-3.128.504-4.853.504-4.612 0-7.412-1.184-7.412-1.704a.547.547 0 0 0-.005-.073L1.81 5.602c.135.078.28.154.432.227.042.02.086.038.128.057.134.062.272.122.417.18l.179.069c.154.058.314.114.478.168.043.013.084.029.13.043.207.065.423.127.646.187l.176.044c.175.044.353.087.534.127a23.414 23.414 0 0 0 .843.17l.121.023c.252.045.508.085.768.122.071.011.144.02.216.03.2.027.4.053.604.077l.24.027c.245.026.49.05.74.07l.081.009c.275.022.552.04.83.056l.233.012c.21.01.422.018.633.025a33.088 33.088 0 0 0 2.795-.026l.232-.011c.278-.016.555-.034.83-.056l.08-.008c.25-.02.497-.045.742-.072l.238-.026c.205-.024.408-.05.609-.077.07-.01.141-.019.211-.03.261-.037.519-.078.772-.122l.111-.02c.215-.04.427-.082.634-.125l.212-.047c.186-.041.368-.085.546-.13l.166-.042c.225-.06.444-.122.654-.189.04-.012.077-.026.115-.038a10.6 10.6 0 0 0 .493-.173c.058-.021.114-.044.17-.066.15-.06.293-.12.43-.185.038-.017.079-.034.116-.052.153-.073.3-.15.436-.228l-.976 7.245c-2.488-.78-5.805-2.292-7.311-3a1.09 1.09 0 0 0-1.088-1.085c-.6 0-1.088.489-1.088 1.088 0 .6.488 1.089 1.088 1.089.196 0 .378-.056.537-.148 1.72.812 5.144 2.367 7.715 3.15zm-7.42-20.047c5.677 0 9.676 1.759 9.75 2.736l-.014.113c-.01.033-.031.067-.048.101-.015.028-.026.057-.047.087-.024.033-.058.068-.09.102-.028.03-.051.06-.084.09-.038.035-.087.07-.133.105-.04.03-.074.06-.119.091-.053.036-.116.071-.177.107-.05.03-.095.06-.15.09-.068.036-.147.073-.222.11-.059.028-.114.057-.177.085-.084.038-.177.074-.268.111-.068.027-.13.054-.203.082-.097.036-.205.072-.31.107-.075.026-.148.053-.228.079-.111.035-.233.069-.35.103-.085.024-.165.05-.253.073-.124.034-.258.065-.389.098-.093.022-.181.046-.278.068-.139.032-.287.061-.433.091-.098.02-.191.041-.293.06-.155.03-.32.057-.482.084-.1.018-.198.036-.302.052-.166.026-.342.048-.515.072-.11.014-.213.03-.325.044-.181.023-.372.041-.56.06-.11.012-.218.025-.332.036-.188.016-.386.029-.58.043-.122.009-.24.02-.364.028-.207.012-.422.02-.635.028-.12.005-.234.012-.354.016a35.605 35.605 0 0 1-2.069 0c-.12-.004-.234-.011-.352-.016-.214-.008-.43-.016-.637-.028-.122-.008-.238-.02-.36-.027-.195-.015-.394-.028-.584-.044-.11-.01-.215-.024-.324-.035-.19-.02-.384-.038-.568-.06l-.315-.044c-.176-.024-.355-.046-.525-.073-.1-.015-.192-.033-.29-.05-.167-.028-.335-.055-.494-.086-.096-.018-.183-.038-.276-.056-.151-.032-.305-.062-.45-.095-.09-.02-.173-.043-.26-.064-.138-.034-.277-.067-.407-.102-.082-.022-.157-.046-.235-.069a11.75 11.75 0 0 1-.368-.108c-.075-.024-.141-.049-.213-.073-.11-.037-.223-.075-.325-.113-.067-.025-.125-.051-.188-.077-.096-.038-.195-.076-.282-.115-.06-.027-.11-.054-.166-.08-.08-.039-.162-.077-.233-.116-.052-.028-.094-.055-.142-.084-.063-.038-.13-.075-.185-.113-.043-.029-.075-.058-.113-.086-.048-.037-.098-.073-.139-.11-.032-.029-.054-.057-.08-.087-.033-.035-.069-.07-.093-.104-.02-.03-.031-.058-.046-.086-.018-.035-.039-.068-.049-.102l-.015-.113c.076-.977 4.074-2.736 9.748-2.736zm12.182 12.124c-.118-.628-.84-1.291-2.31-2.128l.963-7.16a.531.531 0 0 0 .005-.073C22.16 1.581 16.447 0 11.32 0 6.194 0 .482 1.581.482 3.851a.58.58 0 0 0 .005.072L2.819 21.25c.071 2.002 5.236 2.75 8.5 2.75 1.805 0 3.615-.188 5.098-.531.598-.138 1.133-.3 1.592-.48 1.18-.467 1.789-1.053 1.813-1.739l.945-7.018c.557.131 1.016.197 1.389.197.54 0 .902-.137 1.134-.413a.956.956 0 0 0 .21-.804Z"/></svg>
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  # In Development Sites
  - name: Dev Web
    url: https://dev.everythingbagel.me
    expectedStatusCodes:
      - 200
    maxResponseTime: 3000

  - name: The Empty
    url: https://test.everythingbagel.me
    expectedStatusCodes:
      - 200
      - 201
      - 404
    commitMessages:
      readmeContent: ":pencil: Update summary in README [skip ci] [upptime]"
      summaryJson: ":card_file_box: Update status summary [skip ci] [upptime]"
      statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci] [upptime]"
      graphsUpdate: ":bento: Update graphs [skip ci] [upptime]"
    maxResponseTime: 5000
   
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.everythingbagel.me
  # favicon: https://everythingbagel.me/images/logo.png
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"
  robotsText: |
    # See http://www.robotstxt.org/robotstxt.html for documentation on how to use the robots.txt file
    # For the complete list of user agents, visit https://status.everythingbagel.me/robots.txt
    # Block unauthorised use of this site as training material for AI
    # FAANG
    User-agent: Amazonbot
    Disallow: /
    User-agent: Applebot
    Disallow: /
    User-agent: FacebookBot
    Disallow: /
    ## Microsoft / OpenAI
    User-agent: GPTBot
    Disallow: /
    User-agent: ChatGPT-User
    Disallow: /
    ## Google
    User-agent: Google-Extended
    Disallow: /
    User-agent: AdsBot-Google
    Disallow: /
    # Others
    User-agent: anthropic-ai
    Disallow: /
    User-agent: Claude-Web
    Disallow: /
    User-agent: cohere-ai
    Disallow: /
    User-agent: Bytespider
    Disallow: /
    User-agent: Diffbot
    Disallow: /
    User-agent: Mediapartners-Google
    Disallow: /
    ## Common Crawl
    User-agent: CCBot
    Disallow: /
    User-agent: The Knowledge AI
    Disallow: /
    User-agent: Omgilibot
    Disallow: /
    User-agent: Omgili
    Disallow: /
    User-agent: panscient.com
    Disallow: /
    User-agent: PetalBot
    Disallow: /
    User-agent: Turnitin
    Disallow: /
    User-agent: PerplexityBot
    Disallow: /
    User-agent: YouBot
    Disallow: /
    # Default directives for specific User-agents
    User-agent: *
    Disallow: /media_proxy/
    Disallow: /interact/
    # Default directives for all other User-agents
    Disallow:
    # Wait 5 seconds between successive requests
    Crawl-delay: 5
    
  #theme: night #dark, light, night, ocean
  themeUrl: https://everythingbagel.me/css/dark.css
  apiBaseUrl: https://api.github.com
  #baseUrl: /upptime
  logoUrl: https://everythingbagel.me/images/bagel-banner.png
  name: Everything Monitor
  introTitle: "Website Status of the *Everything Bagel Realms*"
  introMessage: Welcome to the endpoint monitor of live databases.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: http://everythingbagel.me
    - title: Wiki
      href: http://wiki.everythingbagel.me
      
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  url: "Websites"
  footer: "Copyright © 2003-2024 Nathan Sparrow. All Rights Reserved.  \n**Everything Monitor** is a status page which uses **real-time** data from our [open source]($REPO), powered entirely by [GitHub](https://upptime.js.org/).  \nNo server required — just GitHub Actions, Issues, and Pages."
  activeIncidents: "Paw-sitive Updates: Active Incidents"
  allSystemsOperational: "🟢 Everything is in the paws of the purrfect system!"
  degradedPerformance: "🟡 Degraded Purrformance"
  completeOutage: "🔴 Complete Cat-astrophes"
  partialOutage: "🟠 Partial Cat-astrophes"
  incidentTitle: "Incident $NUMBER: Dive into the Details!"
  incidentDetails: "Detailed Overview of the Incident"
  incidentFixed: "All fixed up! 🎉"
  incidentOngoing: "Still in progress, hang tight! ⏳"
  incidentOpenedAt: "Incident opened at"
  incidentClosedAt: "Closed at"
  incidentViewOnGitHub: "🖥️ View and Subscribe on GitHub"
  incidentCommentSummary: "Commented at $DATE by $AUTHOR"
  incidentBack: "← Back to All Pawsitive Updates"
  pastIncidents: "Past Paw-sitive Cat-astrophes"
  pastIncidentsResolved: "✅ Resolved in $MINUTES minutes! ($POSTS posts)"
  liveStatus: "🐾 Current Status Purrformance!"
  overallUptimeTitle: "Overall Uptime Overview"
  averageResponseTimeTitle: "Average Response Time Insights"
  sevenDayResponseTime: "7-Day Response Time Report"
  history: "History"
  responseTimeMs: "Response Time (ms) - How fast are we?"
  responseTimeDay: "24-hour response time"
  responseTimeWeek: "7-day response time"
  responseTimeMonth: "30-day response time"
  responseTimeYear: "1-year response time"
  liveStatusHtmlComment: "<!--live status-->"
  uptime: "All-time uptime"
  uptimeDay: "24-hour uptime"
  uptimeWeek: "7-day uptime"
  uptimeMonth: "30-day uptime"
  uptimeYear: "1-year uptime"
  up: "Up and Running! 🚀"
  down: "⚫ Consumed by the Void! We'll be back soon!"
  degraded: "Degraded Performance. We’re on it!"
  loading: "🐾 Loading... Hang tight!"
  rateLimitExceededIntro: "You've hit the request limit for the hour. Patience is a virtue!"
  rateLimitExceededWhatDoesErrorMean: "What does this mean?"
  rateLimitExceededErrorMeaning: "This website uses the GitHub API to fetch real-time status. You’ve hit the default limit of 60 requests/hour."
  rateLimitExceededErrorHowCanFix: "How can I solve this?"
  rateLimitExceededErrorFix: "Wait for the limit to reset or add a GitHub Personal Access Token for extra requests!"
  rateLimitExceededGeneratePAT: "Here's how to generate a Personal Access Token"
  rateLimitExceededHasSet: "You've already got a personal access token set!"
  rateLimitExceededRemoveToken: "Remove token if necessary"
  rateLimitExceededGitHubPAT: "Your GitHub Personal Access Token"
  rateLimitExceededCopyPastePAT: "Copy & Paste Your Token Here"
  rateLimitExceededSaveToken: "Save Token for Future Requests"
  errorTitle: "Oops! An Error Occurred 🐾"
  errorIntro: "We hit a snag while fetching the latest status."
  errorText: "Please try again in a few moments."
  errorHome: "Return to Dust"
  pastScheduledMaintenance: "Past Feline Fixes 🛠️"
  scheduledMaintenance: "Future Purrformance Checks"
  scheduledMaintenanceSummaryStarted: "Started at $DATE for $DURATION minutes. Stay tuned!"
  scheduledMaintenanceSummaryStarts: "Starts at $DATE for $DURATION minutes. Prepare for downtime!"
  startedAt: "Started at"
  startsAt: "Starts at"
  duration: "Duration"
  durationMin: "$DURATION minutes (We’ll be back before you know it!)"
  incidentCompleted: "Incident Completed Successfully! 🎉"
  incidentScheduled: "Incident Scheduled: Mark Your Calendars!"
  duration24H: "24 Hours"
  duration7D: "7 Days"
  duration30D: "30 Days"
  duration1Y: "1 Year"
  durationAll: "All Time"
  locale: "en-US"

workflowSchedule:
    graphs: "0 0 * * *"
    responseTime: "0 23 * * *"
    staticSite: "0 1 * * *"
    summary: "0 0 * * *"
    updateTemplate: "0 0 * * *"
    updates: "0 3 * * *"
    uptime: "*/5 * * * *"
